
import type { Metadata } from 'next'
import {Poppins} from 'next/font/google'
import Nav from './components/Nav'
import './globals.css'
import 'bootstrap/dist/css/bootstrap.min.css'


const poppins = Poppins({
  weight:['400','700'],
  subsets:['latin']
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const  RootLayout = ({
  children,
}: {
  children: React.ReactNode
}) => {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Nav/>
        {children} 
      </body>
    </html>
  )
}
export default RootLayout