import './globals.css'
import type { Metadata } from 'next'
import {Poppins} from 'next/font/google'
import Nav from './components/Nav'
import 'bootstrap/dist/css/bootstrap.min.css'
import {ProductsContextProvider} from '@/app/Context/productContext'
import { AuthContextProvider } from './Context/authContext'
import { CommentContextProvider } from './Context/commentContext'
import { disableReactDevTools } from '@fvilers/disable-react-devtools'


const poppins = Poppins({
  weight:['500','700'],
  subsets:['latin']
});
disableReactDevTools()
export const metadata: Metadata = {
  title: 'Trendify',
  description: 'Generated by create next app',
}

const  RootLayout = ({
  children,
}: {
  children: React.ReactNode
}) => {
  return (
    <html lang="en">
      <body className={poppins.className}>
      <CommentContextProvider>
      <AuthContextProvider>
      <ProductsContextProvider>
         <Nav/>
        {children}
      </ProductsContextProvider>
      </AuthContextProvider>
    </CommentContextProvider>
      </body>
    </html>
  )
}
export default RootLayout